name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build -t go-pduckdb/integ -f ./internal/integ/Dockerfile .

      - name: Run integration tests
        run: docker run --rm go-pduckdb/integ
